GET http://localhost:1001/api/companies

###

GET http://localhost:1001/api/companies/64ad4ec8d6d1537a79c2ec5e

###

POST http://localhost:1001/api/companies
Content-Type: application/json

{
    "Name":"SalesForce",
    "Cg_Criteria":7.3,
    "Domain":"SDE"
}

###

DELETE http://localhost:1001/api/companies/64ad4ec8d6d1537a79c2ec5e

###

PATCH  http://localhost:1001/api/companies/64ae394bc42cb7c5110a272a
Content-Type: application/json

{
    "Cg_Criteria":7.79
}





